### ISSUE TITLE
convert to exe with pyinstaller, output not work

### ISSUE THREAD

**Issue by zablah** [rootm0s/WinPwnage#62] opened 2020-03-03 06:56 UTC
I'm trying to convert this project to exe file with` pyinstaller --onefile winpwnage.py`  command
the process was complete successfully , but when execute the exe file in dist folder not thing is happen, and there is no output to screen

**Comment by rootm0s** [comment] 2020-03-03 14:54
Tested it and it seems to be broken at the moment. Thanks for letting me know!

Feel free to test it with python2 and py2exe instead.

**Comment by cclauss** [comment] 2020-03-28 16:09
Does #64 fix this situation?  Python 2 went end of life on 1/1/2020 so should we streamline the Travis CI process and drop support for Python 2?  If not now, when?

**Comment by rootm0s** [comment] 2020-03-28 16:28
Im not sure, havent tested it. Will do it later on!

Python2 is needed for Pupy which uses WinPwnage as a module. Not sure if we should keep supporting it in the future because of the end-of-life of Python 2.

**Comment by rootm0s** [comment] 2020-03-28 16:31
@AlessandroZ Is Pupy supporting Python3?

**Comment by rootm0s** [comment] 2020-03-29 00:38
@zablah This will be resolved in a future fix. Caused by "winpwnage.py" name, if you change it to something else.

Example:

- Name `winpwnage.py` to `main.py`
- Rerun: `pyinstaller --onefile main.py`

**Closed** 2020-03-29 00:38 UTC
Labels: bug

**Comment by rootm0s** [comment] 2020-03-29 00:46
Fixed in:
https://github.com/rootm0s/WinPwnage/commit/039cb560ca8f46aedc1c727c5038239d6f7ccdb8

**Comment by AlessandroZ** [comment] 2020-03-29 15:58
> @AlessandroZ Is Pupy supporting Python3?

Not yet: https://github.com/n1nj4sec/pupy/issues/822

**Comment by rootm0s** [comment] 2020-03-29 17:56
@AlessandroZ Alright, will keep it until you have merged the code.

**Comment by rocketscientist911** [comment] 2020-10-20 10:27
I am having the same issue 

`118 INFO: PyInstaller: 4.0
119 INFO: Python: 3.8.2
134 INFO: Platform: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
135 INFO: wrote /home/pwn/oscp/privesc/WinPwnage/main.spec
143 INFO: UPX is not available.
149 INFO: Extending PYTHONPATH with paths
['/home/pwn/oscp/privesc/WinPwnage', '/home/pwn/oscp/privesc/WinPwnage']
200 INFO: checking Analysis
253 INFO: checking PYZ
269 INFO: checking PKG
273 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit/run
273 INFO: checking EXE`

**Comment by rootm0s** [comment] 2020-10-20 15:30
> I am having the same issue
> 
> `118 INFO: PyInstaller: 4.0 119 INFO: Python: 3.8.2 134 INFO: Platform: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29 135 INFO: wrote /home/pwn/oscp/privesc/WinPwnage/main.spec 143 INFO: UPX is not available. 149 INFO: Extending PYTHONPATH with paths ['/home/pwn/oscp/privesc/WinPwnage', '/home/pwn/oscp/privesc/WinPwnage'] 200 INFO: checking Analysis 253 INFO: checking PYZ 269 INFO: checking PKG 273 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit/run 273 INFO: checking EXE`

I always build on Windows, seems like you're building on Linux?

**Comment by rocketscientist911** [comment] 2020-10-20 18:59
> > I am having the same issue
> > `118 INFO: PyInstaller: 4.0 119 INFO: Python: 3.8.2 134 INFO: Platform: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29 135 INFO: wrote /home/pwn/oscp/privesc/WinPwnage/main.spec 143 INFO: UPX is not available. 149 INFO: Extending PYTHONPATH with paths ['/home/pwn/oscp/privesc/WinPwnage', '/home/pwn/oscp/privesc/WinPwnage'] 200 INFO: checking Analysis 253 INFO: checking PYZ 269 INFO: checking PKG 273 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit/run 273 INFO: checking EXE`
> 
> I always build on Windows, seems like you're building on Linux?

Yes, I have tried on Windows now and it builds the .exe although its not working for me. ?

![image](https://user-images.githubusercontent.com/48825290/96631843-4c09ca00-1330-11eb-9dec-ea93b23be481.png)

**Comment by rootm0s** [comment] 2020-10-20 19:38
Im using `Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32`

Tested building and scanning is working fine on Windows 10 1909. Not sure why you're having issues.
